{% set version = "0.4.4" %}

package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: 8a2902c5ea3b131570ea71059861158b1cffe4b87d656939397008fc1251a542


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git

  run:
    - python
    - xarray
    - dill
    - netCDF4
    - cdo !=2.0.0,!=2.0.2,!=2.0.3,!=2.0.4 # [not win]
    - nco
    - ncplot >0.0.4

test:
  imports:
    - nctoolkit

about:
  home: https://nctoolkit.readthedocs.io/en/stable
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python

extra:
  recipe-maintainers:
    - r4ecology
