{% set version = "1.3.3" %}

package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: 781b107ebe841f7db9f165c6536d39a1ee700bdb53ca738651375c3786ebd3db


build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git
    - setuptools

  run:
    - python
    - dill
    - cdo  <2.6.1 # [not win]
    - nco
    - datashader
    - multiprocess # [osx]
    - ncplot  >=0.3.6
    - jupyter_bokeh  >=3.0.7
    - geoviews  <=1.14.0


test:
  imports:
    - nctoolkit

about:
  home: https://pmlmodelling.github.io/nctoolkit/
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python

extra:
  recipe-maintainers:
    - robertjwilson
