{% set version = "1.1.11" %}

package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: 8940d87ecb31d16944924aad5a35df8a6df469bce081f0a15761ca93924d3a32


build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git

  run:
    - python
    - dill
    - cdo  !=2.4.1 # [not win]
    - nco
    - datashader # [py<311]
    - multiprocess # [osx]
    - ncplot >=0.3.6
    - jupyter_bokeh >=3.0.7


test:
  imports:
    - nctoolkit

about:
  home: https://nctoolkit.readthedocs.io/en/stable
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python

extra:
  recipe-maintainers:
    - robertjwilson
