{% set version = "0.9.2" %}

package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: 194417e85d23117cc4c1ba0bd8a7e02419ede6fe3d1875285e1c89c97c59ab48


build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git

  run:
    - python
    - dill
    - cdo  !=2.0.0,!=2.0.2,!=2.0.3,!=2.0.4 # [not win]
    - nco
    - datashader # [py<311]
    - ncplot  >=0.2.8


test:
  imports:
    - nctoolkit

about:
  home: https://nctoolkit.readthedocs.io/en/stable
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python

extra:
  recipe-maintainers:
    - robertjwilson
