{% set version = "0.2.3" %}

package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: f7ef27de8a2de5dddb5945957142f749d60e876f4ce8f3ff769c20c6bd58bb88

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv 


requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git

  run:
    - python
    - xarray >=0.14.0
    - panel
    - netCDF4
    - hvplot
    - eccodes <=2.18.0
    - cdo  # [not win]
    - nco
    - ncplot

test:
  imports:
    - nctoolkit

about:
  home: https://nctoolkit.readthedocs.io/en/stable 
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python 


extra:
  recipe-maintainers:
    - r4ecology
