{% set version = "0.9.3" %}

package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: 93de3f1f491a491db045a28d0cee6ba3ae71d5ae27a5afe5ba6ed8073cf4c2e3


build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git

  run:
    - python
    - dill
    - cdo  !=2.0.0,!=2.0.2,!=2.0.3,!=2.0.4 # [not win]
    - nco
    - datashader # [py<311]
    - multiprocess
    - ncplot  >=0.2.8


test:
  imports:
    - nctoolkit

about:
  home: https://nctoolkit.readthedocs.io/en/stable
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python

extra:
  recipe-maintainers:
    - robertjwilson
