{% set version = "0.8.7" %}

package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: 6870aefd0d2c80aab32320e78184011a09a6b7ef226cc69f4e9e72d6bcfa3e3a


build:
  number: 2
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git

  run:
    - python
    - xarray
    - dill
    - netCDF4
    - cdo  !=2.0.0,!=2.0.2,!=2.0.3,!=2.0.4 # [not win]
    - nco
    - datashader # [python <3.11]
    - ncplot  >=0.2.8


test:
  imports:
    - nctoolkit

about:
  home: https://nctoolkit.readthedocs.io/en/stable
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python

extra:
  recipe-maintainers:
    - robertjwilson
