{% set version = "0.2.1" %}

package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: bcd9e21f8c885c90d5937980a4714255d2fc550fd2fa02158ead9ee75ba4518a

build:
  noarch: python
  number: 1
#  skip: True  # [windows]
  script: {{ PYTHON }} -m pip install . -vv 

requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git

  run:
    - python
    - xarray >=0.14.0
    - panel
    - netCDF4
    - hvplot
    - cdo
    - nco

test:
  imports:
    - nctoolkit

about:
  home: https://nctoolkit.readthedocs.io/en/stable 
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python 


extra:
  recipe-maintainers:
    - r4ecology
