{% set version = "0.6.0" %}

package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: b8ae90a8822cd751c7493e17c3e0a4cf30bde400f68678f24b35c6bd0d31ea5e


build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git

  run:
    - python
    - xarray
    - dill
    - plotnine
    - netCDF4
    - cdo !=2.0.0,!=2.0.2,!=2.0.3,!=2.0.4 # [not win]
    - nco
    - ncplot >0.1.0

test:
  imports:
    - nctoolkit

about:
  home: https://nctoolkit.readthedocs.io/en/stable
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python

extra:
  recipe-maintainers:
    - r4ecology
