{% set version = "1.2.6" %}
{% set python_min = "3.10" %}


package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: 974d1b50c7e58c5cda1da079fd4feff61862845d0bf581005cd6527cf6697ff8


build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git
    - setuptools

  run:
    - python
    - dill
    - cdo  !=2.4.1 # [not win]
    - nco
    - datashader
    - multiprocess # [osx]
    - ncplot >=0.3.6
    - jupyter_bokeh >=3.0.7


test:
  imports:
    - nctoolkit

about:
  home: https://nctoolkit.readthedocs.io/en/stable
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python

extra:
  recipe-maintainers:
    - robertjwilson
