{% set version = "1.1.5" %}

package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: 840f6701c47bfac410d323334644ca24e794e3e659e4a9f35cfaf73b6ae7e74c


build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git

  run:
    - python
    - dill
    - cdo  >=2.0.5 # [not win]
    - nco
    - datashader # [py<311]
    - multiprocess
    - ncplot >=0.3.6
    - jupyter_bokeh >=3.0.7


test:
  imports:
    - nctoolkit

about:
  home: https://nctoolkit.readthedocs.io/en/stable
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python

extra:
  recipe-maintainers:
    - robertjwilson
