{% set version = "1.1.3" %}

package:
  name: nctoolkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nctoolkit/nctoolkit-{{ version }}.tar.gz
  sha256: a70db8a69c273e78e90137552f8c27b62d4149a90cdd1f1a8afa4d2865638d31


build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python
    - pip
    - setuptools_scm
    - setuptools-git

  run:
    - python
    - dill
    - cdo  >=2.0.5 # [not win]
    - nco
    - datashader # [py<311]
    - multiprocess
    - ncplot >=0.3.6
    - jupyter_bokeh >=3.0.7


test:
  imports:
    - nctoolkit

about:
  home: https://nctoolkit.readthedocs.io/en/stable
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Fast and easy analysis of netCDF data in Python

extra:
  recipe-maintainers:
    - robertjwilson
